/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import classe.Matriz;


/**
 *
 * @author franzwagner
 */
public class Tela1 extends javax.swing.JFrame {
    
    Matriz matrizA = null;
    Matriz matrizB = null;

    /**
     * Creates new form tela
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        campoSaidaMatrizB1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoEntradaQtdLinhasMatrizA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoEntradaQtdColunasMatrizA = new javax.swing.JTextField();
        botaoCriarMatrizA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoSaidaMatrizA = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoEntradaQtdLinhasMatrizB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoEntradaQtdColunasMatrizB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoSaidaMatrizB = new javax.swing.JTextPane();
        botaoCriarMatrizB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoSomaMatrizes = new javax.swing.JButton();
        botaoSubtracaoMatrizes = new javax.swing.JButton();
        botaoMultiplicacaoMatrizes = new javax.swing.JButton();
        botaoMatrizTransposta = new javax.swing.JButton();
        botaoPotenciaMatriz = new javax.swing.JButton();
        botaoMultiplicacaoMatrizAporK = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoSaidaOperacao = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaBool = new javax.swing.JTable();

        jScrollPane3.setViewportView(campoSaidaMatrizB1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matriz");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MATRIZ A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setText("Quantidade de Linhas");

        campoEntradaQtdLinhasMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaQtdLinhasMatrizAActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade de Colunas");

        campoEntradaQtdColunasMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaQtdColunasMatrizAActionPerformed(evt);
            }
        });

        botaoCriarMatrizA.setText("Criar");
        botaoCriarMatrizA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarMatrizAActionPerformed(evt);
            }
        });

        campoSaidaMatrizA.setEditable(false);
        campoSaidaMatrizA.setBorder(new javax.swing.border.MatteBorder(null));
        campoSaidaMatrizA.setToolTipText("");
        jScrollPane2.setViewportView(campoSaidaMatrizA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(botaoCriarMatrizA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEntradaQtdColunasMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoEntradaQtdLinhasMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoEntradaQtdLinhasMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoEntradaQtdColunasMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCriarMatrizA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MATRIZ B", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setText("Quantidade de Linhas");

        campoEntradaQtdLinhasMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaQtdLinhasMatrizBActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantidade de Colunas");

        campoEntradaQtdColunasMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEntradaQtdColunasMatrizBActionPerformed(evt);
            }
        });

        campoSaidaMatrizB.setEditable(false);
        campoSaidaMatrizB.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(campoSaidaMatrizB);

        botaoCriarMatrizB.setText("Criar");
        botaoCriarMatrizB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarMatrizBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoEntradaQtdLinhasMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(botaoCriarMatrizB))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEntradaQtdColunasMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoEntradaQtdLinhasMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoEntradaQtdColunasMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(botaoCriarMatrizB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERAÇÕES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        botaoSomaMatrizes.setText("+");
        botaoSomaMatrizes.setToolTipText("Adiciona Matriz A e Matriz B");
        botaoSomaMatrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomaMatrizesActionPerformed(evt);
            }
        });

        botaoSubtracaoMatrizes.setText("-");
        botaoSubtracaoMatrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubtracaoMatrizesActionPerformed(evt);
            }
        });

        botaoMultiplicacaoMatrizes.setText("x");
        botaoMultiplicacaoMatrizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoMatrizesActionPerformed(evt);
            }
        });

        botaoMatrizTransposta.setText("Matriz Transposta");

        botaoPotenciaMatriz.setText("Potenciação da Matriz A");
        botaoPotenciaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPotenciaMatrizActionPerformed(evt);
            }
        });

        botaoMultiplicacaoMatrizAporK.setText("Multiplicação da Matriz A por K");
        botaoMultiplicacaoMatrizAporK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoMatrizAporKActionPerformed(evt);
            }
        });

        campoSaidaOperacao.setEditable(false);
        campoSaidaOperacao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "RESPOSTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane4.setViewportView(campoSaidaOperacao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoSomaMatrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSubtracaoMatrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMultiplicacaoMatrizes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoMatrizTransposta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPotenciaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMultiplicacaoMatrizAporK, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSomaMatrizes)
                    .addComponent(botaoSubtracaoMatrizes)
                    .addComponent(botaoMultiplicacaoMatrizes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMatrizTransposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPotenciaMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMultiplicacaoMatrizAporK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaBool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"É Triangular Superior", "", null},
                {"É Triangular Inferior", null, null},
                {"É Simétrica", null, null},
                {"É Identidade", null, null},
                {"É Ortogonal", null, null},
                {"É de Permutação", null, null},
                {"São Iguais", null, null},
                {"São Diferentes", null, null}
            },
            new String [] {
                "", "Matriz A", "Matriz B"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBool.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tabelaBool);
        if (tabelaBool.getColumnModel().getColumnCount() > 0) {
            tabelaBool.getColumnModel().getColumn(0).setHeaderValue("");
            tabelaBool.getColumnModel().getColumn(1).setHeaderValue("Matriz A");
            tabelaBool.getColumnModel().getColumn(2).setHeaderValue("Matriz B");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoEntradaQtdLinhasMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaQtdLinhasMatrizAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEntradaQtdLinhasMatrizAActionPerformed

    private void campoEntradaQtdColunasMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaQtdColunasMatrizAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEntradaQtdColunasMatrizAActionPerformed

    private void botaoCriarMatrizAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarMatrizAActionPerformed
        // Criar Matriz A 
        try{
            int qLinhas = Integer.parseInt(campoEntradaQtdLinhasMatrizA.getText());
            int qColunas = Integer.parseInt(campoEntradaQtdColunasMatrizA.getText());
            
            matrizA = new Matriz(qLinhas, qColunas);
            
            for(int l = 0; l < qLinhas; l++){
                for(int c = 0; c < qColunas; c++){
                    String msg = "MATRIZ A [" + l + "][" + c + "]";
                    
                    int elemento = Integer.parseInt(JOptionPane.showInputDialog(msg));
                    
                    matrizA.setElemento(l, c, elemento);
                }
            }
            
            campoSaidaMatrizA.setText(matrizA.getMatriz());
            
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_botaoCriarMatrizAActionPerformed

    private void botaoCriarMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarMatrizBActionPerformed
        // Criar Matriz B
        try{
            int qLinhas = Integer.parseInt(campoEntradaQtdLinhasMatrizB.getText());
            int qColunas = Integer.parseInt(campoEntradaQtdColunasMatrizB.getText());
            
            matrizB = new Matriz(qLinhas, qColunas);
            
            for(int l = 0; l < qLinhas; l++){
                for(int c = 0; c < qColunas; c++){
                    String msg = "MATRIZ B [" + l + "][" + c + "]";
                    
                    int elemento = Integer.parseInt(JOptionPane.showInputDialog(msg));
                    
                    matrizB.setElemento(l, c, elemento);
                }
            }
            
            campoSaidaMatrizB.setText(matrizB.getMatriz());
            
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_botaoCriarMatrizBActionPerformed

    private void campoEntradaQtdLinhasMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaQtdLinhasMatrizBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEntradaQtdLinhasMatrizBActionPerformed

    private void campoEntradaQtdColunasMatrizBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEntradaQtdColunasMatrizBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEntradaQtdColunasMatrizBActionPerformed

    private void botaoSomaMatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomaMatrizesActionPerformed
        try{
            Matriz matrizAdicao = matrizA.adicionar(matrizB);
            
            campoSaidaOperacao.setText(matrizAdicao.getMatriz());
            
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_botaoSomaMatrizesActionPerformed

    private void botaoSubtracaoMatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubtracaoMatrizesActionPerformed
        try{
            Matriz matrizSubtracao = matrizA.subtrair(matrizB);
            
            campoSaidaOperacao.setText(matrizSubtracao.getMatriz());
            
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }      
    }//GEN-LAST:event_botaoSubtracaoMatrizesActionPerformed

    private void botaoMultiplicacaoMatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoMatrizesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMultiplicacaoMatrizesActionPerformed

    private void botaoPotenciaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPotenciaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPotenciaMatrizActionPerformed

    private void botaoMultiplicacaoMatrizAporKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoMatrizAporKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMultiplicacaoMatrizAporKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarMatrizA;
    private javax.swing.JButton botaoCriarMatrizB;
    private javax.swing.JButton botaoMatrizTransposta;
    private javax.swing.JButton botaoMultiplicacaoMatrizAporK;
    private javax.swing.JButton botaoMultiplicacaoMatrizes;
    private javax.swing.JButton botaoPotenciaMatriz;
    private javax.swing.JButton botaoSomaMatrizes;
    private javax.swing.JButton botaoSubtracaoMatrizes;
    private javax.swing.JTextField campoEntradaQtdColunasMatrizA;
    private javax.swing.JTextField campoEntradaQtdColunasMatrizB;
    private javax.swing.JTextField campoEntradaQtdLinhasMatrizA;
    private javax.swing.JTextField campoEntradaQtdLinhasMatrizB;
    private javax.swing.JTextPane campoSaidaMatrizA;
    private javax.swing.JTextPane campoSaidaMatrizB;
    private javax.swing.JTextPane campoSaidaMatrizB1;
    private javax.swing.JTextPane campoSaidaOperacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabelaBool;
    // End of variables declaration//GEN-END:variables
}
